version: '3.8'

services:
  # Base image (no auth)
  claudeforge-setup:
    build: .
    image: claudeforge-setup
    container_name: claudeforge-setup
    volumes:
      - .:/home/dev/workspace
    stdin_open: true
    tty: true
    working_dir: /home/dev/workspace
    environment:
      - TERM=xterm-256color

  # Ready-to-dev image (authenticated)
  claudeforge:
    image: claudeforge
    container_name: claudeforge
    volumes:
      - .:/home/dev/workspace
    stdin_open: true
    tty: true
    working_dir: /home/dev/workspace
    environment:
      - TERM=xterm-256color